listVar <- list("Total Alkalinity (uEquiv/l)" = "A.TOT", 
                "BOD5" = "BOD5", 
                "Chlorophyll a (ug/l)" = "Chl.a", 
                "Total CO2" = "CO2", 
                "Density (mmol/l)" = "Density", 
                "Total Ammonium (umol/l)" = "NH4.N", 
                "Nitrite (umol/l)" = "NO2.N", 
                "Nitrate (umol/l)" = "NO3.N",
                "Total Oxidised Nitrogen" = "NO3.N...NO2.N", 
                "Nitrate to Orthophosphate ratio" = "NO3.PO4", 
                "Dissolved Oxygen (umol/l)" = "O2",
                "Oxygen saturation" = "O2_sat", 
                "Organic Nitrogen" = "Org.N", 
                "pH (pH units)" = "pH", 
                "Orthophosphate (umol/l)" = "PO4.P", 
                "Salinity (PSU)" = "SAL",
                "Transparency depth (1)" = "SECCHI", 
                "Silicate (umol/l)" = "SiO3.Si", 
                "Temperature (degC)" = "T", 
                "Total nitrogen (umol/l)" = "TOT.N",
                "Total Nitrogen to Total Phosphorus ratio" = "TOT.N.TOT.P", 
                "Total Phosphorus (umol/l)" = "TOT.P") 

listStation <- list("000F" = "000F", 
                    "000K" = "000K", 
                    "00CZ" = "00CZ",
                    "00MA" = "00MA",
                    "all" = "all")

listDepth <- list("0" = "0", 
                  "5" = "5", 
                  "10" = "10",
                  "15" = "15",
                  "16" = "16",
                  "21" = "21",
                  "24" = "24",
                  "all" = "all")

